<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Shema.io</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="./dist/css/core.css">
        <script src="./dist/js/vendors.bundle.js"></script>
        <script src="./dist/js/app.bundle.js"></script>
    </head>
    <body>
        <h3>Slim</h3>
        <div>a microframework for PHP</div>
        <div class="block--fixed-center">
            <div class="wrapper--padding-15">
                <div class="section--width-1-2">
                    <div class="wrapper--margin-20">
                        <div class="section--width-1-4">
                            <h3>1</h3>
                        </div>
                        <div class="section--width-1-2">
                            <h3>2</h3>
                        </div>
                        <div class="section--width-1-4">
                            <h3>3</h3>
                        </div>
                    </div>
                    <h3>This is</h3>
                </div>
                <div class="section--width-1-2">
                    <h3>Me</h3>
                </div>
            </div>
        </div>
        <div class="jumbo">
            <div class="wrapper">
                <div class="listing-card">
                    <div class="listing-card__inner">
                        <h3>ONE</h3>
                    </div>  
                </div>
                <div class="listing-card">
                    <div class="listing-card__inner">
                       <h3>TWO</h3> 
                    </div>
                </div>
                <div class="listing-card">
                    <div class="listing-card__inner">
                        <h3>THREE</h3>
                    </div>
                </div>
                <div class="listing-card">
                    <div class="listing-card__inner">
                        <h3>FOUR</h3>
                    </div>
                </div>
                <div class="listing-card">
                    <div class="listing-card__inner">
                        <h3>FIVE</h3>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
